
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-admin-ui
  # namespace: prod
  labels:
    app: iam-admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-admin-ui
  # 发布策略-平滑发布
  strategy:
    type: Recreate
    #type: RollingUpdate # 资源不足，不能用滚动方式
    #rollingUpdate:
    #  maxSurge: 25%
    #  maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: iam-admin-ui
    spec:
      imagePullSecrets:
        # 阿里云 Secrets
        - name: aliyun
      containers:
        - name: iam-admin-ui
          # 镜像， flow 会替换此变量
          image: ${IMAGE}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iam-admin-ui-svc
  # namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http-80
  selector:
    app: iam-admin-ui


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # namespace: prod
  name: iam-admin-ui-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: iam-admin.uat.husters.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iam-admin-ui-svc
                port:
                  number: 80
  tls:
    - hosts:
        - iam-admin.uat.husters.cn
      secretName: iam-admin.uat.husters.cn
